import "./indexStyles.scss";
import "./js/gallery/gallery.scss";
import "./layout/header/header.scss";
import "./layout/about/about.scss";
import "./layout/projects/projects.scss";
import "./layout/achievements/achievements.scss";
import "./layout/equipment/equipment.scss";
import "./layout/staff/staff.scss";
import "./layout/footer/footer.scss";
